# -----------------------------------------------------------------------------
# GENERATED FILE - DO NOT EDIT MANUALLY
# This file is automatically generated from templates in docker/templates/
# Changes to this file will be OVERWRITTEN on every commit.
# To make changes, modify the appropriate template:
#   Template: service-dev.hbs
#   Command: yarn run generate:dockerfiles
# -----------------------------------------------------------------------------

FROM node:25.9.0-alpine3.23 AS base
RUN apk upgrade --no-cache --available
ENV COREPACK_HOME=/usr/local/corepack
RUN npm install -g --force corepack \
    && corepack install -g yarn@4.12.0 \
    && chmod -R a+rX "$COREPACK_HOME"

FROM base AS install
WORKDIR /usr/app
COPY package.json .yarnrc.yml yarn.lock .
COPY shared/package.json shared/
COPY services/common/package.json services/common/
COPY services/tenantapi/package.json services/tenantapi/
RUN --mount=type=cache,id=node_modules,target=/root/.yarn YARN_CACHE_FOLDER=/root/.yarn \
    yarn workspaces focus @microrealestate/tenantapi

FROM base
WORKDIR /usr/app
COPY --from=install /usr/app ./
ENTRYPOINT ["yarn", "workspace", "@microrealestate/tenantapi", "run", "dev"]