#!/usr/bin/env tsx

import fs from 'node:fs';
import path from 'node:path';
import Handlebars from 'handlebars';

const PROJECT_ROOT = path.join(process.cwd());

interface DockerConfig {
  defaults: {
    baseImage: string;
    yarnVersion: string;
  };
  services: Record<
    string,
    {
      customTemplate?: boolean;
      hasMongoDBTools?: boolean;
      hasUploadsDir?: boolean;
    }
  >;
  webapps: Record<
    string,
    {
      hasScripts?: boolean;
    }
  >;
}

// Load configuration
const config: DockerConfig = JSON.parse(
  fs.readFileSync(
    path.join(PROJECT_ROOT, 'docker/config/dockerfile-config.json'),
    'utf8'
  )
);

// Register Handlebars helpers
Handlebars.registerHelper(
  'if',
  function (
    this: unknown,
    conditional: boolean,
    options: Handlebars.HelperOptions
  ) {
    if (conditional) {
      return options.fn(this);
    }
    return options.inverse(this);
  }
);

function generateWarningHeader(templateName: string): string {
  return `# -----------------------------------------------------------------------------
# GENERATED FILE - DO NOT EDIT MANUALLY
# This file is automatically generated from templates in docker/templates/
# Changes to this file will be OVERWRITTEN on every commit.
# To make changes, modify the appropriate template:
#   Template: ${templateName}
#   Command: yarn run generate:dockerfiles
# -----------------------------------------------------------------------------`;
}

function getServices(): string[] {
  const servicesDir = path.join(PROJECT_ROOT, 'services');
  const services = fs
    .readdirSync(servicesDir, { withFileTypes: true })
    .filter((dirent) => dirent.isDirectory())
    .map((dirent) => dirent.name)
    .filter((name) => name !== 'common'); // Exclude common package

  return services;
}

function getWebapps(): string[] {
  const webappsDir = path.join(PROJECT_ROOT, 'webapps');
  const webapps = fs
    .readdirSync(webappsDir, { withFileTypes: true })
    .filter((dirent) => dirent.isDirectory())
    .map((dirent) => dirent.name)
    .filter((name) => name !== 'commonui'); // Exclude commonui package

  return webapps;
}

function generateServiceDockerfiles(serviceName: string): void {
  const serviceConfig = config.services[serviceName] || {};
  const templateName = serviceConfig.customTemplate ? serviceName : 'service';

  // Generate production Dockerfile
  const prodTemplate = fs.readFileSync(
    path.join(PROJECT_ROOT, `docker/templates/${templateName}.hbs`),
    'utf8'
  );
  const prodCompiled = Handlebars.compile(prodTemplate);
  const prodContent = prodCompiled({
    serviceName,
    baseImage: config.defaults.baseImage,
    yarnVersion: config.defaults.yarnVersion,
    hasMongoDBTools: serviceConfig.hasMongoDBTools,
    hasUploadsDir: serviceConfig.hasUploadsDir
  });
  const prodWithHeader = `${generateWarningHeader(`${templateName}.hbs`)}\n\n${prodContent}`;

  const prodPath = path.join(
    PROJECT_ROOT,
    `services/${serviceName}/Dockerfile`
  );
  fs.writeFileSync(prodPath, prodWithHeader);

  // Generate development Dockerfile
  const devTemplate = fs.readFileSync(
    path.join(PROJECT_ROOT, `docker/templates/${templateName}-dev.hbs`),
    'utf8'
  );
  const devCompiled = Handlebars.compile(devTemplate);
  const devContent = devCompiled({
    serviceName,
    baseImage: config.defaults.baseImage,
    yarnVersion: config.defaults.yarnVersion,
    hasMongoDBTools: serviceConfig.hasMongoDBTools
  });
  const devWithHeader = `${generateWarningHeader(`${templateName}-dev.hbs`)}\n\n${devContent}`;

  const devPath = path.join(
    PROJECT_ROOT,
    `services/${serviceName}/dev.Dockerfile`
  );
  fs.writeFileSync(devPath, devWithHeader);

  console.log(`✅ Generated Dockerfiles for service: ${serviceName}`);
}

function generateWebappDockerfiles(appName: string): void {
  const appConfig = config.webapps[appName] || {};

  // Generate production Dockerfile
  const prodTemplate = fs.readFileSync(
    path.join(PROJECT_ROOT, `docker/templates/webapp.hbs`),
    'utf8'
  );
  const prodCompiled = Handlebars.compile(prodTemplate);
  const prodContent = prodCompiled({
    appName,
    baseImage: config.defaults.baseImage,
    yarnVersion: config.defaults.yarnVersion,
    hasScripts: appConfig.hasScripts
  });
  const prodWithHeader = `${generateWarningHeader('webapp.hbs')}\n\n${prodContent}`;

  const prodPath = path.join(PROJECT_ROOT, `webapps/${appName}/Dockerfile`);
  fs.writeFileSync(prodPath, prodWithHeader);

  // Generate development Dockerfile
  const devTemplate = fs.readFileSync(
    path.join(PROJECT_ROOT, `docker/templates/webapp-dev.hbs`),
    'utf8'
  );
  const devCompiled = Handlebars.compile(devTemplate);
  const devContent = devCompiled({
    appName,
    baseImage: config.defaults.baseImage,
    yarnVersion: config.defaults.yarnVersion,
    hasScripts: appConfig.hasScripts
  });
  const devWithHeader = `${generateWarningHeader('webapp-dev.hbs')}\n\n${devContent}`;

  const devPath = path.join(PROJECT_ROOT, `webapps/${appName}/dev.Dockerfile`);
  fs.writeFileSync(devPath, devWithHeader);

  console.log(`✅ Generated Dockerfiles for webapp: ${appName}`);
}

function validateDockerfiles(): void {
  const errors: string[] = [];

  // Check if all generated Dockerfiles exist and are non-empty
  const services = getServices();
  const webapps = getWebapps();

  for (const service of services) {
    const prodPath = path.join(PROJECT_ROOT, `services/${service}/Dockerfile`);
    const devPath = path.join(
      PROJECT_ROOT,
      `services/${service}/dev.Dockerfile`
    );

    if (!fs.existsSync(prodPath) || fs.statSync(prodPath).size === 0) {
      errors.push(
        `Missing or empty production Dockerfile for service: ${service}`
      );
    }

    if (!fs.existsSync(devPath) || fs.statSync(devPath).size === 0) {
      errors.push(
        `Missing or empty development Dockerfile for service: ${service}`
      );
    }
  }

  for (const webapp of webapps) {
    const prodPath = path.join(PROJECT_ROOT, `webapps/${webapp}/Dockerfile`);
    const devPath = path.join(PROJECT_ROOT, `webapps/${webapp}/dev.Dockerfile`);

    if (!fs.existsSync(prodPath) || fs.statSync(prodPath).size === 0) {
      errors.push(
        `Missing or empty production Dockerfile for webapp: ${webapp}`
      );
    }

    if (!fs.existsSync(devPath) || fs.statSync(devPath).size === 0) {
      errors.push(
        `Missing or empty development Dockerfile for webapp: ${webapp}`
      );
    }
  }

  if (errors.length > 0) {
    console.error('❌ Dockerfile validation failed:');
    for (const error of errors) {
      console.error(`  - ${error}`);
    }
    process.exit(1);
  }

  console.log('✅ All Dockerfiles validated successfully');
}

function main(): void {
  const args = process.argv.slice(2);
  const validateOnly = args.includes('--validate-only');

  if (validateOnly) {
    validateDockerfiles();
    return;
  }

  console.log('🔄 Regenerating Dockerfiles from templates...');

  // Generate service Dockerfiles
  const services = getServices();
  for (const service of services) {
    generateServiceDockerfiles(service);
  }

  // Generate webapp Dockerfiles
  const webapps = getWebapps();
  for (const webapp of webapps) {
    generateWebappDockerfiles(webapp);
  }

  // Validate generated files
  validateDockerfiles();

  console.log('✅ All Dockerfiles regenerated successfully');
}

main();
