# -----------------------------------------------------------------------------
# GENERATED FILE - DO NOT EDIT MANUALLY
# This file is automatically generated from templates in docker/templates/
# Changes to this file will be OVERWRITTEN on every commit.
# To make changes, modify the appropriate template:
#   Template: webapp-dev.hbs
#   Command: yarn run generate:dockerfiles
# -----------------------------------------------------------------------------

FROM node:25.9.0-alpine3.23 AS base
RUN apk upgrade --no-cache --available
ENV COREPACK_HOME=/usr/local/corepack
RUN npm install -g --force corepack \
    && corepack install -g yarn@4.12.0 \
    && chmod -R a+rX "$COREPACK_HOME"

FROM base AS deps
WORKDIR /usr/app
COPY package.json .yarnrc.yml yarn.lock .
COPY shared/package.json shared/package.json
COPY webapps/commonui/package.json webapps/commonui/package.json
COPY webapps/tenant/package.json webapps/tenant/package.json
RUN --mount=type=cache,id=node_modules,target=/root/.yarn YARN_CACHE_FOLDER=/root/.yarn \
    yarn workspaces focus @microrealestate/tenant

FROM base
ENV NEXT_TELEMETRY_DISABLED=1
WORKDIR /usr/app
COPY --from=deps /usr/app ./
ENTRYPOINT ["sh", "-c", "yarn workspace @microrealestate/tenant run dev -p $PORT"]