export type EnvironmentValues = {
  LOGGER_LEVEL?: string;
  PRODUCTION?: boolean;
  PORT?: number;
  MONGO_URL?: string;
  REDIS_URL?: string;
  REDIS_PASSWORD?: string;
  ACCESS_TOKEN_SECRET?: string;
  REFRESH_TOKEN_SECRET?: string;
  RESET_TOKEN_SECRET?: string;
  CIPHER_KEY?: string;
  CIPHER_IV_KEY?: string;
  DEMO_MODE?: boolean;
  EXPOSE_FRONTENDS?: boolean;
  AUTHENTICATOR_URL?: string;
  API_URL?: string;
  PDFGENERATOR_URL?: string;
  RESETSERVICE_URL?: string;
  LANDLORD_FRONTEND_URL?: string;
  LANDLORD_BASE_PATH?: string;
  TENANT_FRONTEND_URL?: string;
  TENANT_BASE_PATH?: string;
  DOMAIN_URL?: string;
  CORS_ENABLED?: boolean;
  TENANTAPI_URL?: string;
};
